### ISSUE TITLE
Don't Copy Paste Other Peoples Code

### ISSUE THREAD

**Issue by ElectronicsArchiver** [Hummel009/Game-of-Thrones#8]
It seems you do not know how GitHubs Pull Request system works.

Pull requests are opened to merge content from one 
repository into another, such as a contributors 
repository into it's origin.

Pull requests are finished by either being closed
and thus rejecting the proposed changes or merging
those changes into the base repository.

You however copy pasted my #7, effectively stealing
my work and robbing me from my contribution.

Merging a pull request gives the contributor
attribution by the repositories commit history
as well as contribution section.

I hope this was part of you not understanding 
GitHub workings and not a malicious action.

1. Please correct your mistake by reverting your
   [copy pasted commit] and instead merging the PR.

2. Informing yourself on how GitHub works 
   and thinks you shouldn't do.
   
   
[copy pasted commit]: https://github.com/Hummel009/Game-of-Thrones/commit/1a77f30736f2c4b38bb42cf79bcb25b75dd61ee8

**Comment by Hummel009** [comment]
I'm sorry, I'm not well versed in the work of this service. Thank you for pointing out my mistake. I tried to do the right thing now. It seems like I've done everything well now.

I'm also sorry that I didn't answer for a long time, I didn't know that the number above means an unread message.

**Comment by ElectronicsArchiver** [comment]
Thank you for fixing your mistake.

If you now know, thats good at least~

**Comment by ElectronicsArchiver** [comment]
@Hummel009 If you ever need help with GitHub, let me know~
